---
- name: Converge
  hosts: all
  vars:
    log4shell_scan_path: /tmp

  pre_tasks:
    - name: Download vulnerable Rundeck
      get_url:
        url: https://download.rundeck.org/war/rundeck-3.3.12-20210521.war
        dest: "{{ log4shell_scan_path }}/rundeck.war"
        mode: '0440'
  roles:
    - role: claranet.log4shell
